### ISSUE TITLE
install-yarn runs into cert issue (workaround: curl insecure)

### ISSUE THREAD

**Issue by olleolleolle** [CircleCI-Public/node-orb#106]
## Orb version:

circleci/node@4.7.0

## What happened:

```
- node/install:
    install-yarn: true
    install-npm: false
    node-version: 16.13.0
    yarn-version: 1.22.17
```

led to:

```
Selected version of Yarn is 1.22.17
Checking if YARN is already installed...
Installing YARN v1.22.17

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
mv: cannot stat 'yarn-v1.22.17/*': No such file or directory
```

## Expected behavior:

an installed yarn.

## Additional Information:

I found a workaround and a possible explanation for why this failed to install

https://discuss.circleci.com/t/yarn-install-failing-node-orb/41477
