### ISSUE TITLE
Cannot run `node/install-packages` running using a Ramdisk

### ISSUE THREAD

**Issue by tomsquest** [CircleCI-Public/node-orb#119]
## What happened:

Cannot run `node/install-packages` running using a Ramdisk ([CircleCI doc](https://circleci.com/docs/2.0/executor-types/#ram-disks)).

Extract from config.yml:

```
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - node/install-packages
```

Error:
```
ln: failed to create hard link '/tmp/node-project-lockfile' => 'package-lock.json': Invalid cross-device link
```

## Expected behavior:

Running in a Ramdisk should still allow to install packages.

## Additional Information:

Full error:

```
#!/bin/bash -eo pipefail
if [ -f "package-lock.json" ]; then
  echo "Found package-lock.json file, assuming lockfile"
  ln package-lock.json /tmp/node-project-lockfile
elif [ -f "npm-shrinkwrap.json" ]; then
  echo "Found npm-shrinkwrap.json file, assuming lockfile"
  ln npm-shrinkwrap.json /tmp/node-project-lockfile
elif [ -f "yarn.lock" ]; then
  echo "Found yarn.lock file, assuming lockfile"
  ln yarn.lock /tmp/node-project-lockfile
fi
ln package.json /tmp/node-project-package.json

Found package-lock.json file, assuming lockfile
ln: failed to create hard link '/tmp/node-project-lockfile' => 'package-lock.json': Invalid cross-device link

Exited with code exit status 1

CircleCI received exit code 1
```

config.yml:

```
version: 2.1

orbs:
  node: circleci/node@5

jobs:
  build:
    docker:
      - image: cimg/node:14.18.1
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - node/install-packages:
          include-branch-in-cache-key: false
```

Edit: upgraded to circleci/node@5
