### ISSUE TITLE
yarn-install fails on macos

### ISSUE THREAD

**Issue by MasterOdin** [CircleCI-Public/node-orb#143]
## What happened:

Using the following configuration:
```yml
  mac:
    macos:
      xcode: '11.4'
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - run:
          name: Install git lfs
          command: |
            if ! [ -x "$(command -v git-lfs)" ]; then
              brew install git-lfs
            fi
            git lfs install

      - checkout

      - run:
          name: git lfs pull
          command: git lfs pull

      - run:
          name: Setup dependencies
          command: brew install unixodbc gnupg coreutils mmv

      - node/install:
          node-version: '16.14'
          install-yarn: true
```

The `node/install` fails when trying to run the "Install Yarn" step. The output for that step is:
```
# bash source code...

Latest version of Yarn is 1.22.18
Checking if YARN is already installed...
A different version of Yarn is installed (1.22.4); removing it
Installing YARN v1.22.18

Exited with code exit status 60
```

Not sure why or where it's failing, and it's not like I'm doing anything that exciting with the configuration before that point I feel. The workflow this is happening on is a private project.

## Expected behavior: 

That yarn would install correctly.
