### ISSUE TITLE
Permission denied while restore npm cache 

### ISSUE THREAD

**Issue by lu911** [CircleCI-Public/node-orb#158]
## What happened:

Getting "Permission Denied" while restore npm cache.

error:
```
Found a cache from build 859 at node-deps-arch1-linux-amd64-6_106-v2-develop-XdJ1g_ahUn0RDtSmEalhzFrcTZXR2yOAu+BGa+T52zI=
Size: 61 MiB
Cached paths:
  * /home/circleci/.npm

Downloading cache archive...
Validating cache...

Unarchiving cache...
Skipping writing "home/circleci/.npm/_cacache/content-v2/sha1/04/5f/9782d011ae9a6803ddd382b24392b3d890f7" - open /home/circleci/.npm/_cacache/content-v2/sha1/04/5f/9782d011ae9a6803ddd382b24392b3d890f7: permission denied
```

config.yml:
```
version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  deploy:
    working_directory: ~/tmp
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - attach_workspace:
          at: ~/tmp
      - node/install:
          node-version: '14.17.3'
      - node/install-packages:
          override-ci-command: npm install
          cache-version: v3
      - deploy:
          name: Deploy
          command: |
            ...
```

## Expected behavior:

The cache is restored without errors.

## Additional Information:

**Comment by whanwells** [comment]
This seems to only occur when using a machine image (at least in my experience).

**Comment by eaviles** [comment]
I was having this issue too, in my experience it seems like when using a machine image it sometimes picks up hosts with cached files from other pipeline runs. I got around the issue by deleting the `~/.npm` folder before trying to restore the cache…

```yaml
- run: rm -rf ~/.npm
- node/install-packages
```

Funny enough, it seems to happen with other tools like nvm. The cache (`/opt/circleci/.nvm/.cache`) has already a bunch of files when starting the machine.

**Comment by whanwells** [comment]
> ```yaml
> - run: rm -rf ~/.npm
> - node/install-packages
> ```

This worked for me as well. Thanks for the tip @eaviles!

**Comment by KyleTryon** [comment]
Hey folks, sorry for the delay. I have replicated the issue and working with the image folks to see what we can do.

**Comment by DominicGBauer** [comment]
@KyleTryon has there been any progress on this issue?

**Comment by KyleTryon** [comment]
This image had been resolved, we should have closed this issue. Are you experiencing this again? Is it also on the machine? @DominicGBauer

**Comment by warrenronsiek** [comment]
I'm experiencing this issue with the following:
```
jobs:
  test:
    docker:
      - image: cimg/node:21.7.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
```

the proposed workarounds don't work for me: `'/home/circleci/.npm': No such file or directory`
