### ISSUE TITLE
Allow upgrade of resource_class for orb jobs

### ISSUE THREAD

**Issue by matt-dalton** [CircleCI-Public/node-orb#160]
## Describe Request:
For the [node run/test jobs](https://circleci.com/developer/orbs/orb/circleci/node#jobs) I would like to be able to increase the size of the instance from medium to large/xlarge.

Am I missing an existing way to do this?

## Examples:
```
workflows:
    run_all_jobs:
        - node/test:
                  name: test
                  version: *tag
                  pkg-manager: yarn
                  test-results-for: jest
                  esource_class: xlarge # Would like to be able to change this
                  requires:
                      - previous_job
```

## Supporting Documentation Links:
https://circleci.com/developer/orbs/orb/circleci/node#jobs
