### ISSUE TITLE
Cache dependencies by workflow instead of job

### ISSUE THREAD

**Issue by goldylucks** [CircleCI-Public/node-orb#166]
## Describe Request:
Would be nice to have this api:
```
      - node/install-packages:
          pkg-manager: yarn
          cache-path: ~/home/circleci/
          cache-version: "v1.2"
          cache-by: "workflow" # default is "job"
```

ATM the cache key contains the job name, and I'd like too my jobs to share the cache.
