### ISSUE TITLE
Cannot install Node on MacOS executor

### ISSUE THREAD

**Issue by MichaelMarner** [CircleCI-Public/node-orb#18]
### Orb version

1.1.6

### What happened

Attempting to run `node/install` on a MacOS executor is failing due to missing `gpg` and `sha256sum` commands. Here is the relevant section of the CircleCI config:

```yaml
  build-ios:
    macos:
      xcode: '11.1.0'
    working_directory: ~/repo
    steps:
      - checkout
      - node/install:
          node-version: '10.16.3'
```

And the output from running the job:

```
Selected version of Node.js is 10.16.3
A different version of Node.js is installed (v12.10.0); removing it
Importing Node.js trusted release keys...
/bin/bash: line 155: gpg: command not found
/bin/bash: line 164: sha256sum: command not found
grep: SHASUMS256.txt: No such file or directory
```

### Expected behavior

The node installation should complete successfully.

**Comment by MichaelMarner** [comment]
As a workaround, installing gpg and sha256sum with Brew fixes the issue, but adds another 4:20 to the build time:

```yaml
      - run:
          name: Install nvm deps
          command: brew install gnupg coreutils
```
