### ISSUE TITLE
Inability to install requested NodeJS version does not break the build

### ISSUE THREAD

**Issue by roblillack** [CircleCI-Public/node-orb#192]
## Orb version:

circleci/node@5.1.0

## What happened:

Both the "Install Node.js" and "Activate installed node version" steps are marked as successful—even though both of them failed.

<img width="1254" alt="image" src="https://github.com/CircleCI-Public/node-orb/assets/37167/2eeb7ef5-f98d-4022-9e5d-49168a4625e1">

Workflow: https://app.circleci.com/pipelines/github/vizzlo/web/20167/workflows/add62e32-3990-4089-bf53-857b132fc7bd/jobs/95940

## Expected behavior:

Break the build, if the requested Node version cannot be installed for whatever reason

**Comment by marboledacci** [comment]
Hi @roblillack I noticed you are using windows with bash here, by default unix executors add the `-eo pipefail` to the shell, so this is granted. For windows, you have to manually add this when setting the shell.
The correct way to get the behavior you want would be:

```yaml
    machine:
      image: 'windows-server-2022-gui:current'
      resource_class: windows.medium
      shell: bash.exe -eo pipefail
```

If you are using the windows orb, it would be the same, just add `-eo pipefail` after bash.exe.
