### ISSUE TITLE
Yarn install failed with permission denied 

### ISSUE THREAD

**Issue by duknic** [CircleCI-Public/node-orb#241]
## Orb version:
6.3.0

## What happened:

Setting `install-yarn: true` in node-orb config causes error when orb attempts to install a newer version of yarn.

### Error

```
Latest version of Yarn is 1.22.22
Checking if YARN is already installed...
A different version of Yarn is installed (1.22.19); removing it
^@^@rm: cannot remove '/usr/local/bin/yarn': Permission denied

Exited with code exit status 1
```

## Expected behaviour:

node-orb should be able to install newer versions of yarn on the container without error

### config.yml

```
version: 2.1
orbs:
  ruby: circleci/ruby@2.2.1
  node: circleci/node@6.3.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.3.5-browsers
        environment:
          - STUFF=things
      - image: cimg/postgres:10.21-postgis
        environment:
          - STUFF=things

    steps:
      - checkout
      - ruby/install-deps
      - node/install: 
          install-yarn: true
          node-version: '22.11.0'
      - node/install-packages:
          pkg-manager: yarn
```
