### ISSUE TITLE
Switching to 7.0.0 fails (unexpected argument: version)

### ISSUE THREAD

**Issue by ronkorving** [CircleCI-Public/node-orb#247]
## Orb version:

7.0.0

## What happened:

I made a pull request in my project to switch the Orb version from 6.3.0 to 7.0.0 and the file now won't even run:

```
Error calling workflow: 'test_on_pr'
Error calling job: 'node/run'
Unexpected argument(s): version
```

## Expected behavior:

The job should run using the version of Node.js I provide.

## Additional Information:

It's a major version bump of the orb, but the [7.0.0 release notes](https://github.com/CircleCI-Public/node-orb/releases/tag/v7.0.0) don't mention anything that would cause this. Although they're quite vague ("add extra features"), so who knows.

Was `version` removed? If so, was that intentional? What's the simplest way to supply a version now?

**Comment by ronkorving** [comment]
In the mean time I've discovered this PR which removed `version`: https://github.com/CircleCI-Public/node-orb/pull/244

So apparently I need to provide an executor now instead of a version. That works for me. I already happen to have the perfect executor in my config file, defined under `executors` as follows:

```yaml
  aws_cdk_executor:
    docker:
      - image: cimg/node:<< pipeline.parameters.nodejs_version >>
        environment:
          AWS_REGION: ap-northeast-1
    working_directory: ~/my-project
```

But my `node/run` job with `executor: aws_cdk_executor` fails:

```
Unknown variable(s): pipeline.parameters.nodejs_version
```

That same executor works fine in 3 jobs I have already defined in my config file, am using a daily basis and haven't changed in ages.

Could someone, perhaps @marboledacci , advise on what I can and cannot provide as executor to `node/run`?

**Comment by marboledacci** [comment]
Hi @ronkorving thanks for the feedback on the release notes, it's not clear the version parameter removal, I will update the notes.
As for your problem, is there any difference in the way you are defining this job and the others? Or the way you are calling it?

**Comment by ronkorving** [comment]
The executor is defined as above, and the job is defined as follows:

```yaml
      - node/run:
          name: openapi_lint
          app-dir: api-doc
          npm-run: lint
          executor: aws_cdk_executor
          requires: [dependencies]
```

This used to work:

```yaml
      - node/run:
          name: openapi_lint
          app-dir: api-doc
          npm-run: lint
          version: << pipeline.parameters.nodejs_version >>
          requires: [dependencies]
```

**Comment by marboledacci** [comment]
This looks like a problem on the way CircleCI manages the pipeline parameters. Pipeline parameters are not supported with orbs. In this case it would look like the parameter is not used in the orb directly, but apparently the executor is passed to the orb without expanding the parameter, and as I said, orbs don't support pipeline parameters.
I suggest you to update your code like this

```yaml
parameters:
  nodejs_version:
    type: string
    default: lts

executors:
  param_executor:
    parameters:
      version:
        type: string
        default: lts
    docker:
      - image: cimg/node:<< parameters.version >>
        environment:
          AWS_REGION: ap-northeast-1  

workflows:
  wf:
    jobs:
      - node/test:
          executor: 
            name: param_executor
            version: << pipeline.parameters.nodejs_version >>
```

This way, the pipeline parameter is expanded in the executor, and the orb doesn't receive any pipeline parameter.
