### ISSUE TITLE
"Install pnpm" step fails with EACCES error

### ISSUE THREAD

**Issue by cideM** [CircleCI-Public/node-orb#251]
## Orb version:

circleci/node@7.0.0

## What happened:

```
Selected version of pnpm is 9.12.3
Checking if pnpm is already installed...
A different version of pnpm is installed (9.15.4); removing it
^@^@Installing pnpm v9.12.3
npm error code EACCES
npm error syscall mkdir
npm error path /usr/local/lib/node_modules/pnpm
npm error errno -13
npm error Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/pnpm'
```

## Expected behavior:

No error

## Additional Information:

The command in question is this:

```yaml
commands:
  install-deps:
    steps:
      - node/install-pnpm:
          version: "9.12.3"
      - run: node -v
      - run: pnpm install --frozen-lockfile
```

It sees that pnpm 9.15.4 is already installed and removes it using `sudo`. But the [following `npm i` step](https://github.com/CircleCI-Public/node-orb/blob/6938c3ab99b8df33391ea1bb6eaa0d753170740f/src/scripts/install-pnpm.sh#L41) does not use `sudo` and fails. Re-running the step with `ssh` and using `sudo` manually works:

```shell
circleci@2daadb00cd54:~/project$ sudo npm i -g pnpm@9.12.3

added 1 package in 821ms

1 package is looking for funding
  run `npm fund` for details
```

It's strange that no one else has reported this issue yet so I'm inclined to believe that we're doing something wrong here but there's not much we are doing actually.

The job that is using this `install-deps` step is:

```yaml
jobs:
  run-tests:
    executor:
      name: node/default
      tag: "23.7.0"
    resource_class: medium
    parallelism: 1
    steps:
      - install-deps # <-- this fails
      - run:
          command: |
            JEST_JUNIT_ADD_FILE_ATTRIBUTE=true NODE_OPTIONS=--experimental-vm-modules pnpm exec jest --ci --verbose --runInBand
          name: Run Tests
          environment:
            LOGLEVEL: "debug"
      - store_test_results:
          path: ./report/report.xml
      - store_artifacts:
          path: ./report/report.xml
```
