### ISSUE TITLE
Starting from 2.x version it's not possible to install Node dependencies with custom commands/flags

### ISSUE THREAD

**Issue by KnupMan** [CircleCI-Public/node-orb#29]
### Orb version

2.0.2

### What happened

After switching from 1.x version, I lose the possibility to run custom steps while installing Node dependencies. Before I used for specifying some flags for `yarn install` command. I tried also to add `yarn install` command to `package.json` scripts, but that didn't work properly since it's running `yarn install` as usual first and then custom `yarn install` from package.json.
Here is an example of how I installed the deps before:
```yaml
  install_deps:
    steps:
      - node/with-cache:
          cache-version: v1
          cache-key: yarn.lock
          dir: ~/repo/node_modules
          use-strict-cache: true
          steps:
            - run: yarn install --pure-lockfile --ignore-scripts --no-progress
```
And to install just prod deps:
```yaml
  install_deps:
    steps:
      - node/with-cache:
          cache-version: v1
          cache-key: yarn.lock
          dir: ~/repo/node_modules
          use-strict-cache: true
          steps:
            - run: yarn install --prod --pure-lockfile --ignore-scripts --no-progress
```

### Expected behavior

I want to be able to run a custom command or at least flags for the package manager while installing the dependencies.

```yaml
  install_deps:
    steps:
      - node/install-packages:
          app-dir: ~/repo
          cache-version: v1
          cache-key: yarn.lock
          override-ci: true
          override-ci-flags: --prod --pure-lockfile
          pkg-manager: yarn
```
Or

```yaml
  install_deps:
    steps:
      - node/install-packages:
          app-dir: ~/repo
          cache-version: v1
          cache-key: yarn.lock
          override-ci: true
          override-ci-command: yarn install --prod --pure-lockfile --ignore-scripts --no-progress
          pkg-manager: yarn
```
