### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by kmalakoff** [CircleCI-Public/node-orb#32]
### Orb version

2.0.3

### What happened

Version check fails on windows

### Expected behavior

Script should work on all platforms including windows

This [line](https://github.com/CircleCI-Public/node-orb/blob/master/src/commands/install.yml#L64) fails on windows when trying to produce a cross-platform matrix script. 

Here's my config (adapted from one of the CircleCI blogposts):

```
version: 2.1

executors:
  windows: win/default
  node: node/default

orbs:
  node: circleci/node@2.0.3
  win: circleci/windows@2.2.0

jobs:
  test:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - node/install:
          node-version: '<< parameters.node-version >>'
          install-yarn: false
          install-npm: false
      - run: npm install
      - run: npm test

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              os: [node, windows]
              node-version: ['0.10.48', '0.12.18', '6.17.1', '8.17.0', '10.20.1', 'current', 'latest']
```

Error messages:

```
Missing '(' after 'if' in if statement.
At line:13 char:7
+   if [[ latest == "" || latest == "latest" || latest == "current" ]]; ...
+       ~
Missing type name after '['.
At line:13 char:22
+   if [[ latest == "" || latest == "latest" || latest == "current" ]]; ...
+                      ~~
```

I'm not sure if I'm doing this wrong or if I have unrealistic expectations! Let me know!

**Comment by KyleTryon** [comment]
Hello @kmalakoff,

This orb in its current state would not work on Windows, unless perhaps you were looking to install Node in the WSL portion of Windows.

This orb in its current form expects that it will be running in a terminal shell (not powershell), which allows it to work on MacOS and Linux. We could implement a windows specific node orb or Windows versions of the commands in this orb.

This is an incredibly cool and efficient config setup you have here however, I would love to get to the point of supporting this. 

In this configuration, is not node attempting to install itself on the node docker image too?

Between Linux and Mac I think the configuration you have will work, I am not sure if it will be possible to get something _As_ simple when windows is involved, we may at minimum need to separate those jobs with separate commands.

**Comment by KyleTryon** [comment]
I believe the new advanced conditionals may allow us to bake in Windows support automatically now. Looking into this.

https://discuss.circleci.com/t/advanced-logic-in-config/36011

**Comment by kmalakoff** [comment]
Thank you for the updates Kyle. 

I spent some time going down the rabbit hole of running Node.js in a cross-platform way (nave, nvm, nvm-windows, etc) and decided to write cross-platform scripts directly in JavaScript given your base images come pre-installed with Node.js.

I released a couple of modules:

1) install Node.js: https://github.com/kmalakoff/node-install-release. 

$ nri [version string]

2) run a specific version of Node.js: https://github.com/kmalakoff/node-version-use

$ nvu [version string] [command and arguments]

If you can assume Node.js is already installed in the base image, it might be easier to write in JavaScript.

**Comment by brandonros** [comment]
```
version: 2.1
orbs:
  win: circleci/windows@2.2.0
  node: circleci/node@4.1.0
jobs:
  build:
    executor:
      name: win/default
      shell: bash.exe
    working_directory: ~/repo/electron
    steps:
      - checkout
      - node/install
      - run:
          name: Update NPM
          command: "npm.exe install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: "npm.exe install"
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Generate Builds
          command: "npm.exe run build:windows"
      - store_artifacts:
          path: ~/repo/out/make
```

so, this doesn't work? :(
