### ISSUE TITLE
Feature: Accept multiple cache paths

### ISSUE THREAD

**Issue by lbalmaceda** [CircleCI-Public/node-orb#53]
## Describe Request:
👋  I was updating a project to run integration tests with Cypress. Cypress requires browsers installed in order to run the tests, and I understand neither versions v2, v3, and v4 of this orb will help me until support for browser image variants is provided for the "newer" docker images of nodejs. 
![image](https://user-images.githubusercontent.com/3900123/92275367-61807d00-eec5-11ea-81be-54f42ab27a9e.png)

So I stuck to v1 and all was good so far. Eventually, I ran into a caching issue because cypress since v3 and up is installing itself in the `.cache` folder, rather than in the `node_modules` folder as any other node package (see doc link). This orb, and I think every version of it, doesn't allow me to specify **multiple cache paths**. It defaults to `.npm` and does allow to override it, but not to specify more than one.

**Is passing a list value possible?** and, would you consider that change?

The alternatives I have today are:
- Using this orb on v1 and add an extra step to globally install the cypress binary, instead of delegating that to the `npm ci` command.
- Haven't tested, but I assume I could still use this orb on v1 and manually call the `save_cache` step passing the `.cache` folder key. Would look odd since I'm running those inside a "with-cache" named step that is supposed to take care of that for me.
- Not using orbs, write the whole config script as usual. The downside is the verbosity.

## Supporting Documentation Links:
- Cypress NPM caching docs: https://docs.cypress.io/guides/guides/continuous-integration.html#Caching
- Orb v1 / with-cache: https://circleci.com/orbs/registry/orb/circleci/node?version=1.1.6#commands-with-cache

**Comment by TheLudd** [comment]
Is this also needed for yarn workspace projects where there can be multiple `node_modules` folders?

**Comment by kylemh** [comment]
@gmemstr I see that you added the hacktoberfest label. Can you add the topic label as well?

**Comment by leonardomorenozaga** [comment]
+1

```
steps:
    - save_cache:
        key: node-deps-<<parameters.cache-version>>-<<#parameters.include-branch-in-cache-key>>{{ .Branch }}-<</parameters.include-branch-in-cache-key>>{{ checksum "/tmp/node-project-lockfile" }}
        paths:
            - <<parameters.cache-path>>
```
There might be different _paths_ you may be interested in caching in your setup (like triggering pipelines through Circle hooks pre-building static stuffs), workspaces projects and other use cases would be benefit just exposing the same param type it's used on `paths`, a list.
