### ISSUE TITLE
Yarn install does not use the cache-path parameter

### ISSUE THREAD

**Issue by patatepartie** [CircleCI-Public/node-orb#61]
## Orb version:

4.1.0

## What happened:

I have the following configuration:
```yaml
version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  test:
    docker:
      - image: cimg/node:12.18.2
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          cache-path: ~/.cache/yarn

workflows:
  test:
    jobs:
      - test:
          context:
            - docker-hub-creds
```

There is, unfortunately, no visual way to describe what I *think* is happening, because `yarn install`'s output is the same whether the dependencies are cached or not. Only the duration can be an indicator, but it's too variable between jobs to be reliable.

If I understand correctly the code, when `cache-path` is specified, that's the path which will be cached by `save_cache`.
That path is, however, not used by `yarn install`, unless I override the command with `override-ci-command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn`.

## Expected behavior:

The `yarn install` command uses the cache directory specified by `cache-path`.
Alternatively, the documentation could be clarified to explain that the install command needs to be overridden with `override-ci-command` to specify the cache folder.
Currently the documentation for the `cache-path` parameter is confusing for yarn users:

> By default, this orb will utilize 'npm ci' and cache the '~/.npm' directory. Override which path to cache with this parameter.

## Additional Information:

AFAIK, this is also true for `npm`.
I haven't used recent versions of `npm` and I don't know how its cache works, though.
