### ISSUE TITLE
Please consider using several partial keys in restore_cache

### ISSUE THREAD

**Issue by julienw** [CircleCI-Public/node-orb#63]
## Describe Request:

It is very common, and actually recommended in the CircleCI documentation, that we specify several keys in `restore_cache`, so that the cache can be reused and primed even if the underlying lock files change.

For example, Here is a real-life configuration from my project:

Saving is:
```
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
```

Restoring is:
```
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - v2-dependencies-{{ checksum "package.json" }}-
            - v2-dependencies-
```

But this isn't what the orb is doing:
https://github.com/CircleCI-Public/node-orb/blob/a8e41866cd2f9680992719851ec38533db6281cb/src/commands/install-packages.yml#L62-L67
https://github.com/CircleCI-Public/node-orb/blob/a8e41866cd2f9680992719851ec38533db6281cb/src/commands/install-packages.yml#L100-L105

Is there a drawback to always doing this? Or should we make this a configuration option?

I'd be happy looking at this if there is consensus about it.

Thanks!
