### ISSUE TITLE
Node fails to install on macos

### ISSUE THREAD

**Issue by MasterOdin** [CircleCI-Public/node-orb#65]
## Orb version:

This failure was observed using 4.0.1 and 4.1.0. The failure went away under 3.0.1 as that version does not use nvm, so looks like a nvm error. I did not investigate further so as to not waste my mac minutes and that 3.0.1 worked.

## What happened:

```
#!/bin/bash --login -eo pipefail
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
NVM_DIR="$HOME/.nvm"
echo "export NVM_DIR=\"$HOME/.nvm\"" >> $BASH_ENV
echo "[ -s \"$NVM_DIR/nvm.sh\" ] && \. \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
source $BASH_ENV
nvm install \
 12.13.1  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13527  100 13527    0     0   209k      0 --:--:-- --:--:-- --:--:--  213k
=> Downloading nvm from git to '/Users/distiller/.nvm'
=> Cloning into '/Users/distiller/.nvm'...
remote: Enumerating objects: 290, done.        
remote: Counting objects: 100% (290/290), done.        
remote: Compressing objects: 100% (257/257), done.        
remote: Total 290 (delta 34), reused 110 (delta 20), pack-reused 0        
Receiving objects: 100% (290/290), 163.37 KiB | 4.54 MiB/s, done.
Resolving deltas: 100% (34/34), done.
=> Compressing and cleaning up git repository

=> Appending nvm source string to /Users/distiller/.bashrc
=> Appending bash_completion source string to /Users/distiller/.bashrc
N/A: version "12.13.0 -> N/A" is not yet installed.

You need to run "nvm install 12.13.0" to install it before using it.
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
N/A: version "12.13.0 -> N/A" is not yet installed.

You need to run "nvm install 12.13.0" to install it before using it.

Exited with code exit status 3
CircleCI received exit code 3
```

## Expected behavior:

Node would be installed, and build would not fail

## Additional Information:

Stripped down build config:
```
version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    macos:
      xcode: '11.4'
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1

    steps:
      - checkout

      - run:
          name: Setup dependencies
          command: brew install unixodbc gnupg coreutils

      - node/install:
          install-yarn: true
          node-version: "12.13.1"

workflows:
  version: 2
  build:
    jobs:
      - build
```
