### ISSUE TITLE
Yarn 2 support

### ISSUE THREAD

**Issue by PiDelport** [CircleCI-Public/node-orb#69]
The orb currently supports Yarn 1, but requires these parameter overrides to work with Yarn 2:

```yaml
# Yarn 2 deprecates "--frozen-lockfile" in favour of "--immutable"
override-ci-command: yarn install --immutable

# Yarn 2 uses this rather than "node_modules"
cache-path: .yarn/cache
```

It would be good if the orb supports Yarn 2 natively; perhaps by adding a Yarn 2 option to the `pkg-manager` parameter?
