### ISSUE TITLE
Impossible to install yarn on a container with a user

### ISSUE THREAD

**Issue by cyrilchampier** [CircleCI-Public/node-orb#74]
## Orb version:
4.1.1

## What happened:
This configuration fails:
```
      - node/install:
          install-yarn: true
          install-npm: false
          node-version: 14.15.2
```
Because we defined a "USER" in our image, and that sudo is not available.

## Expected behavior:
yarn install with the current user, without trying to sudo.

## Additional Information:
Due to this line:
https://github.com/CircleCI-Public/node-orb/blob/master/src/scripts/install-yarn.sh#L1
