### ISSUE TITLE
node/install options "lts: true" not set the lts version as default

### ISSUE THREAD

**Issue by berviantoleo** [CircleCI-Public/node-orb#82]
## What happened:

I add node/install like this:

```
- node/install:
       install-yarn: true
       install-npm: false
       lts: true
```

But, the lts version not set as default.

This is the example evidence: https://app.circleci.com/pipelines/github/berv-uni-project/tweety-ui/34/workflows/f5060f49-1048-47d3-b6d4-8d73b897278f/jobs/34

## Expected behavior:

The lts version will be default.
