### ISSUE TITLE
Cache based on .pnpm-lock.yaml

### ISSUE THREAD

**Issue by clarkenciel** [CircleCI-Public/node-orb#89]
## Describe Request:

It would be nice to be able to cache based on `.pnpm-lock.yaml` when using `pnpm` as a package manager in the `install-packages` command.
Granted, this might amount to "npm support."

## Examples:

```yaml
jobs:
  test:
    - run:
        name: install pnpm
        command: sudo npm i -g pnpm
    - checkout
    - node/install-packages:
        override-ci-command: pnpm i
        cache-path: ~/.pnpm-store
```

## Supporting Documentation Links:

[`pnpm` CI integration docs](https://pnpm.io/continuous-integration)
