### ISSUE TITLE
Both `pnpm` and `yarn` do not populate package binaries after package installation

### ISSUE THREAD

**Issue by bugron** [CircleCI-Public/node-orb#96]
## Orb version:

circleci/node@4.7.0

## What happened:
Neither `pnpm` nor `yarn` do not populate binaries after installing dependencies. So for example after `pnpm install` or `yarn` commands `eslint` is not available when invoking with either of them in `package.json` scripts. Only after installing those packages globally are they available to run. Below is a screenshot of the failing job.
<img width="628" alt="image" src="https://user-images.githubusercontent.com/13225220/134851418-9feae407-8ae8-4d47-97a4-c287aa0a77d2.png">
I've also tried to SSH and checked myself. Binaries are actually not created for some reason. See the screenshot.
![image](https://user-images.githubusercontent.com/13225220/134851606-89c43cab-3075-4829-a64b-43465deda015.png)

Also here is part of the config that defines that job:
```yaml
version: 2.1
orbs:
  node: circleci/node@4.7.0
...
jobs:
  dev_eslint:
    executor:
      name: node/default
      tag: 'lts'
    steps:
      - checkout
      - run:
          name: Node.js version
          command: node --version
      - run:
          name: Install pnpm@6
          command: |
            yarn global add pnpm esbuild
            pnpm config set store-dir ~/.pnpm-store
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "pnpm-lock.yaml" }}
      - node/install-packages:
          override-ci-command: pnpm install
          with-cache: false
      - save_cache:
          paths:
            - ~/.pnpm-store
          key: v1-deps-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Run ESLint project-wide
          command: |
            export TIMING=1 && pnpm prettier:client:base --check
            pnpm eslint:client --quiet && pnpm lint:css
            pnpm prettier:server:base --check
            pnpm eslint:server --quiet
            pnpm prettier:common:base --check
            pnpm eslint:common --quiet
```

I had issues with installing `pnpm` the way their docs suggest that global install was not permitted so I found myself using `yarn global add pnpm` which actually succeeded.

Let me know if you need more details.

## Expected behavior:
Create package binaries and successfully invoke from `package.json` scripts.
